### ISSUE TITLE
GitHub Repository Setup Checklist

### ISSUE THREAD

**Issue by konradpa** [MarieBouwgena/uni#2]
Hi,

As part of the [Version Control Course](https://lennartwittkuhn.com/version-control-course-uhh-ss24/), please ensure your repository meets the following criteria. 
You can check the boxes for tasks you complete/tasks you have already completed:

- [x] **Add a `.gitignore` file**  
  Include a `.gitignore` file with appropriate content. [Example `.gitignore` file](https://github.com/lnnrtwttkhn/recipes/blob/main/.gitignore)

- [x] **Create a `recipes.qmd` file**  
Add a `recipes.qmd` file with some content. This should be one or more recipes or to demonstrate the use of Quarto format.

- [x] **Update the `README.md` file**  
Ensure your `README.md` contains sensible content about your project. 
This should include a brief description.

- [x] **Completed Pull Request from a Collaborator**  
Ensure you have a merged Pull Request (PR) from a collaborator who is also part of this course.

- [x] **Clean Repository**  
Your repository should be free from unnecessary files such as empty `.txt` files or other clutter.

Feel free to address these issues directly on GitHub or using your preferred workflow.

If you have any questions or need assistance, don't hesitate to ask.

Best Regards,
Konrad

**Note**
You do not have to complete all tasks until next week´s session (3.6.).
